const GET_USERS = 'GET_USERS';
const GET_LOGIN_USER = 'GET_USER';
const IS_AUTH_USER = 'IS_AUTH_USER';
const IS_FORBIDDEN='IS_FORBIDDEN';
const GET_ONE_ESTABLISHMENTS = 'GET_ONE_ESTABLISHMENTS';
const SET_USER_NAME='SET__USER_NAME'

export {
    GET_USERS,
    SET_USER_NAME,
    GET_ONE_ESTABLISHMENTS,
    GET_LOGIN_USER,
    IS_AUTH_USER,
    IS_FORBIDDEN,
};