const GET_USERS = 'GET_USERS';
const GET_LOGIN_USER = 'GET_USER';
const DELETE_USER = 'DELETE_USER'
const IS_AUTH_USER = 'IS_AUTH_USER';
const GET_ESTABLISHMENTS = 'GET_ESTABLISHMENTS';
const GET_ONE_ESTABLISHMENTS = 'GET_ONE_ESTABLISHMENTS';
const GET_USERS_ESTABLISHMENTS = 'GET_USERS_ESTABLISHMENTS';
const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const ADMIN_APPLICATION = 'ADMIN_APPLICATION';
const SET_REVIEWS = 'SET_REVIEWS';

export {
    GET_USERS,
    GET_ESTABLISHMENTS,
    GET_ONE_ESTABLISHMENTS,
    GET_USERS_ESTABLISHMENTS,
    SET_SEARCH_VALUE,
    GET_LOGIN_USER,
    DELETE_USER,
    IS_AUTH_USER,
    ADMIN_APPLICATION,
    SET_REVIEWS
};